### PR TITLE
Provide TARGET_* defines for boards

### PR DESCRIPTION
**Pull request by adamgreen**
Now provide one of the following defines to the compiler based on
board type:
    TARGET_SMOOTHIE2
    TARGET_BAMBINO210E
    TARGET_BAMBINO200E

### CODE REVIEW

**Comment by arthurwolf** [comment]
Thanks a lot !

If I might suggest something ( not sure how much sense it makes ).
What you are calling "Smoothie2" here is v2-pro-proto1. It's actually using a different setup from what the finished boards will, and there are only two in the world ( yours and the one mark has ). Though it's useful having a type for it, definitely, maybe we should give it a specific name so that when we start actually compiling for real "Smoothie2" boards the name is not taken ?
The "final" v2 boards will be LPC4330, with a 64MBit MX25L6445, talking via SPIFI in quad-spi mode, btw, in case that's important for some reason.

**Comment by adamgreen** [comment]
Maybe SMOOTHIE2_PROTO1 for current board?

**Comment by arthurwolf** [comment]
Yes I think that'd be great.

On Mon, Jul 4, 2016 at 11:34 AM, Adam Green notifications@github.com
wrote:

> Maybe SMOOTHIE2_PROTO1 for current board?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/Smoothieware/Smoothie2/pull/25#issuecomment-230248233,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAGpFR09eg6o38g5QvNe1DEcvt8zs_70ks5qSNOrgaJpZM4JEFBu
> .

## 

Courage et bonne humeur.

**Comment by adamgreen** [comment]
Hold off on the merge then. I will update later in the day and push up a revised version.

**Comment by arthurwolf** [comment]
Cool, thanks.

**Comment by adamgreen** [comment]
@arthurwolf I have added a commit to this PR which renames the Smoothie2 board target.

**Comment by arthurwolf** [comment]
Great, merging :)

**Pull request merged**
