### PR TITLE
Fixes an issue causing the Bambino 210E to stall when executing G1

### PR DESCRIPTION
**Pull request by kasandell**
•Adds a define in the Bambino 210E section of the makefile to prevent execution of the statement that causes the Bambino to stall
•G1 no longer stalls, and M114 shows the correct movement was made by G1

### CODE REVIEW

**Comment by adamgreen** [comment]
Why is this required? It seems kind of hacky to go into the mbed SDK to disables all Tickers when you must be just experiencing a problem with a specific ticker in the Smoothie firmware itself.

**Comment by arthurwolf** [comment]
Hey @kasandell 
It's cool that you found this solves the G1 problem, however I don't think we want to merge that in.
If this solves the issue, that means the problem is likely happening somewhere in a time, and "disabling all timers" is not a long-term solution to that problem :)
You likely want to keep that in your fork while you explore the rest of the firmware ( so that it runs even though the bug is still there ), or to re-enable timers and look at where exactly in the timers the bug is happening.
Did you get MRI to work ? I expect it'd be very useful to debug this.

Cheers.

**Comment by kasandell** [comment]
@arthurwolf the cable I have is shredded so I'll need to order a new one before I can use MRI. @adamgreen you're right, I went way too low in the codebase for this fix, I should've kept it up in the module that doesn't work. On that note, how is Smoothie supposed to handle not having something hooked up? This stall arises when a stepper motor is added to the list of active motors in step ticker, but there are no actual stepper motors hooked up to my bambino.

**Comment by arthurwolf** [comment]
If you have no motors hooked up it should make no difference to Smoothie :
the signals just go nowhere, but that shoudn't cause any kind of trouble

On Fri, Jul 1, 2016 at 6:16 PM, Kyle Sandell notifications@github.com
wrote:

> @arthurwolf https://github.com/arthurwolf the cable I have is shredded
> so I'll need to order a new one before I can use MRI. @adamgreen
> https://github.com/adamgreen you're right, I went way too low in the
> codebase for this fix, I should've kept it up in the module that doesn't
> work. On that note, how is Smoothie supposed to handle not having something
> hooked up? This stall arises when a stepper motor is added to the list of
> active motors in step ticker, but there are no actual stepper motors hooked
> up to my bambino.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/Smoothieware/Smoothie2/pull/22#issuecomment-229987667,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAGpFczSB_fJnaP3ewPRvEVrSOujwz0Tks5qRT1QgaJpZM4JC1zL
> .

## 

Courage et bonne humeur.

**Comment by kasandell** [comment]
Alright.

**Comment by adamgreen** [comment]
Maybe it would be better to close out this PR and instead open up an issue to track everything you know so far about the code not working on the Bambino210E.

**Comment by arthurwolf** [comment]
Yep, closing.

**Comment by adamgreen** [comment]
@kasandell You should definitely open an issue here to describe the G1 bug that you are hitting so that we don't forget about it.

You could try commenting out the following line in your makefile to see if it helps with your issue:

``` makefile
 OPTIMIZATION        :=  0
```

**Pull request closed without merging**
