### PR TITLE
Initial programming/debugging notes

### PR DESCRIPTION
**Pull request by adamgreen**
This is the intial commit of my programming/debugging notes for the
Smoothie2 board itself. I will later create versions of this which are
customized for other boards like the Bambino210E.

### CODE REVIEW

**Comment by kasandell** [comment]
If you need/want some notes for the Bambino 210E, I can send over/create a doc of what I have so far on flashing the bambino.

**Comment by adamgreen** [comment]
@kasandell I will write up an initial version later tomorrow and then you can go in and edit those after they are merged.

**Comment by kasandell** [comment]
Alright, sounds good.

**Comment by arthurwolf** [comment]
Thanks, these have been very useful already in their original location, merging :)

**Comment by adamgreen** [comment]
@kasandell My initial Bambino210E specific notes can be found here: https://github.com/Smoothieware/Smoothie2/blob/master/notes/Bambino210E-board.creole#bambino210e-board-programmingdebugging-notes

@arthurwolf I now link to the Smoothie2 & Bambino210E programming/debugging notes from [here](https://github.com/Smoothieware/Smoothie2#board-specific-programmingdebugging-notes) in the main README.

**Comment by arthurwolf** [comment]
@adamgreen awesome !

**Pull request merged**
